.gitignore, src/lib/functions/opengraph.test.ts, src/lib/functions/opengraph.ts, src/routes/myanimelist/[id]/+page.svelte
Heres how to call it
```html
<script lang="ts">
import { OpengraphGenerator } from '$functions/opengraph';
import { page } from '$app/stores';
const opengraph_html = new OpengraphGenerator({
title: 'Hello',
page_url: $page.url.href,
description: 'random',
site_name: 'CoreProject',
locale: 'en_US'
}).generate_opengraph();
</script>
<svelte:head>
{@html opengraph_html}
</svelte:head>
```
=> Fix opengraph

src/lib/components/pages/home/my_list.svelte
Fix jump to first element on popup hover
=> Fix popup hover issue

src/lib/components/pages/home/my_list.svelte, src/lib/components/shared/scroll_area.svelte, src/lib/functions/opengraph.ts
Closes : https://github.com/sssuneeth/CoreProject-V3-UI/issues/83
=> [`Opengraph`] : Patch

src/tippy.postcss
=> Rewrote Tippy in tailwind language

src/lib/components/pages/anime_info/anime_episodes.svelte, src/routes/user/+layout.svelte
=> Fix Algorithms

src/lib/skeletons/login_page.svelte, src/routes/+page.svelte, src/routes/user/+layout.svelte, src/routes/user/login/+page.svelte, src/routes/user/login/1.svelte, vite.config.ts
=> feat: add skeleton loader for login form

package-lock.json, package.json, src/lib/components/pages/anime_info/anime_episodes.svelte, src/lib/components/shared/scroll_area.svelte, src/routes/user/+layout.svelte
However transitions are not working lol
Take a look at the design
=> style: episode thumbnail card

src/routes/user/+layout.svelte
@baseplate-admin
Seems like he is not working on this lol
=> add: image loader to `/user/` background

src/lib/components/pages/anime_info/index.svelte
=> remove transition css

src/lib/data/mock/latest_animes.ts, src/routes/+page.svelte
=> refactor: add scroll_area instead ellipsis

src/lib/components/pages/anime_info/index.svelte, src/lib/components/shared/image/image.svelte, src/lib/components/shared/image/image_loader.svelte, src/lib/data/mock/anime_list.ts, src/routes/+layout.svelte
What this PR do: 
- Change info card **layout**
- Adds a **glass effect** to header 
- Adds a **radial-gradient** effect on **background**
=> style: new info page resposnive layout

package-lock.json, package.json, src/lib/components/shared/markdown.svelte, src/routes/upload/+page.svelte
Tracking : 
* https://github.com/markedjs/marked-highlight/issues/62
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65891
=> Add hightlight.js support to markdown renderer 

src/lib/components/shared/text_editor.svelte
So the problem is how the caret works, We can try to use positioning but, it doesn't seem to work at all ( probably due to how our site is mostly vw and we are trying to do pixel calculations )
=> fix: try to fix caret

src/lib/components/pages/anime_info/index.svelte, src/lib/data/mock/anime_episodes.ts, src/routes/+page.svelte
Refs : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart
=> style: add better string logic

src/routes/upload/upload_page.svelte
=> fix: main and siblings checkbox logic

src/routes/+layout.svelte
[Screencast from 2023-07-19 00-12-04.webm](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/0181640b-1408-4128-a60d-5f6c9c42409a)
=> fix: vercel effect rapid mouse leave issue

src/lib/components/pages/anime_info/index.svelte
```svelte
{@const resolution = (() => {
switch (episode_resolution) {
case "1080p":
return "fhd";
case "720p":
return "hd";
default:
return "sd";
}
})()}
```
=> make switch case looks more pythony

src/lib/components/tippies/anime_card.svelte, src/lib/components/tippies/my_list_anime_details.svelte, src/routes/+page.svelte, src/routes/explore/+page.svelte
=> style: change tippy

src/lib/components/shared/scroll_area.svelte
Source: 
https://stackoverflow.com/a/54101063
https://stackoverflow.com/a/6165489
=> style: Scrollbar track background

src/nprogress.scss
[Screencast from 2023-08-19 23-35-12.webm](https://github.com/tokitou-san/CoreProject-V3-UI/assets/114811070/aca5221c-e126-4234-b0ac-cc644f58e624)
=> style: Fancy progress bar

src/lib/components/pages/anime_info/index.svelte, src/routes/+page.svelte
Color of genres in anime_info page is changed to primary-500. This fixes #609
=> Changed color of genres in anime_info page

src/lib/components/tippies/my_list_anime_details.svelte, src/routes/+page.svelte
**Changes:**
- Change card style
- Add reveal full title on hover feat.
- Change tippy design
=> style: Change `my list` card style

src/routes/+page.svelte
=> fix: `My list` cards responsive

src/lib/components/shared/scroll_area.svelte, src/routes/+page.svelte, src/routes/explore/+page.svelte
=> fix: Scrollarea mask-bottom

src/lib/components/pages/anime_info/index.svelte, src/lib/components/pages/episode/index.svelte, src/lib/components/shared/comment.svelte, src/lib/components/shared/forum_posts.svelte, src/lib/components/shared/image/image.svelte, src/lib/components/shared/image/image_loader.svelte, src/lib/components/shared/image/intersection_observer.svelte, src/lib/components/shared/markdown.svelte, src/lib/components/shared/vercel_hover.svelte, src/lib/components/tippies/anime_card.svelte, src/lib/components/tippies/my_list_anime_details.svelte, src/lib/components/tippies/profile_dropdown.svelte, src/lib/store/timer.ts, src/routes/+page.svelte, src/routes/[...slugs=myanimelist]/[id=int]/+page.svelte, src/routes/anilist/[id=int]/+page.svelte, src/routes/explore/+page.svelte, src/routes/kitsu/[id=int]/+page.svelte, src/routes/user/login/1.svelte, src/routes/user/register/1.svelte, src/routes/user/register/2.svelte
Removed : 
- TimerStore
- Dead Comments
Refractored : 
- Entire Codebase
- Anilist Page
- Kistu page
=> refractor: codebase

src/lib/components/pages/home/latest_episodes_card.svelte, src/lib/functions/json_to_tree.test.ts, src/lib/functions/json_to_tree.ts, src/routes/+layout.svelte
Closes  : https://github.com/tokitou-san/CoreProject-V3-UI/issues/663
=> feat: convert input to tree

package-lock.json, package.json, src/lib/components/shared/hover_expand.svelte, src/lib/functions/classnames.ts, src/routes/+page.svelte
Creates a component ( `ExpandHover` ) to fix using duplicate codes everywhere.
=> feat: `HoverExpand` component

src/index.test.ts
=> remove unwanted test file

src/lib/components/shared/scroll_area.svelte
Rewrite `ScrollArea` styles into Tailwind class ( arbitrary style ).
Closes #677
=> refactor: write `Scrollarea` styles in tailwind

src/lib/components/pages/home/latest_episodes_card.svelte, src/routes/anime/+page.svelte
Fix creating instance of classes in html
Fixes #679
=> fix: Inline classes in html

src/routes/anime/+layout.svelte, src/routes/anime/+page.svelte
UI for unauthenticated users
Note: for now I added a very basic boolean logic to check if user is logged in or not, we will change this along the line
Closes #193
=> feat: UI for not logged in users

src/routes/+layout.svelte, src/routes/+page.svelte, src/routes/user/+layout.svelte, src/routes/user/login/1.svelte, src/routes/user/login/2.svelte, src/routes/user/register/1.svelte, src/routes/user/register/2.svelte, src/routes/user/register/3.svelte, src/routes/user/reset-password/+page.svelte
Made auth pages layout full screen and fixed broken url paths in auth pages as well.
Fixes #684
=> fix: Auth pages broken layout and url paths

src/lib/components/tippies/profile_dropdown.svelte, src/routes/anime/+layout.svelte
**Note**: Dont merge this now
Closes #590
=> fix: Profile dropdown tippy

src/lib/functions/document/vw.test.ts, vite.config.ts
https://github.com/vitest-dev/vitest/issues/1109
=> feat: add test file specific codes
